import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Mainlayout } from "@/components/Mainlayout.jsx";
import MenuContextProvider from "@/context/MenuContext.jsx";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      >
        <MenuContextProvider>
          <Mainlayout>{children}</Mainlayout>
        </MenuContextProvider>
      </body>
    </html>
  );
}
